### ISSUE TITLE
Conflict with 'rearmed-js/object/select' and React.js

### ISSUE THREAD

**Issue by nequalszero** [westonganger/rearmed-js#1]
The `Object#select` method from `rearmed-js` seems to cause an error when rendering html `<select>` tags using React.

```
Uncaught Invariant Violation: select is a void element tag and must neither have `children` nor use `dangerouslySetInnerHTML`.
```

I am using rearmed-js 1.0.0 and react 15.4.2.

**Comment by westonganger** [comment]
I am thinking that I can change `Object#select` to `Object#keep_if`. 

I would like to keep the object select method. Maybe I will make it opt-in (ie. `import "rearmed-js/dangerous/object/select"`)

**Comment by westonganger** [comment]
I have made changes for this in master.

Can you test master with `require('rearmed-js')` in your project to see if it causes errors anymore.
Once you do `require('rearmed-js/object/dangerous/select')` you should get the error.

If all goes well with the testing I will release v1.0.1 with these changes.

**Comment by nequalszero** [comment]
Just confirmed that the error is now gone with `require('rearmed-js')` and present with `require('rearmed-js/object/dangerous/select')`.  Thanks!

**Comment by westonganger** [comment]
v1.0.1 with these changes will NOT be released. 

I will instead be releasing v1.1.0 which patches object to be much safer (see issue #2). v1.1.0 will feature `Object#select` by default and does not include a `Object#keepIf` method. These new update can be seen on the develop branch for now.
